"""Property-based authorization tests — the answer to "you wrote your own labels".

WHY THIS EXISTS
---------------
A benchmark whose corpus was generated by its own author, with labels planted by
its own author, can score perfectly for a reason that has nothing to do with the
system under test: if the detector keys on exactly the columns the generator used
to plant the fault, the precision is definitional rather than evidential. Our
own corpus has that shape — 1,050 cases across 21 families I chose, with the
right answer decided by the family name.

A bigger corpus of the same construction does not fix that. Ten thousand cases
drawn from twenty-one hand-designed families is twenty-one ideas repeated, not
ten thousand tests.

What fixes it is dropping labels entirely. These tests generate envelopes and
carts from a grammar rather than a fixture, and assert INVARIANTS that must hold
for every input — no expected label, nothing for the author to plant. Hypothesis
searches for a counterexample and shrinks it when it finds one, which means the
adversary is a search procedure rather than my imagination.

That is a different and stronger claim than corpus size, and it is the claim
worth making: not "we tested 1,050 cases" but "we could not construct an input
that violates these properties, and here is the search that tried."

READING A FAILURE
-----------------
A failure here prints a minimal reproducing envelope and cart. It is a real
authorization bug, not a flaky test. Do not add `@example` to route around one.
"""
from __future__ import annotations

import time

import pytest
pytest.importorskip("hypothesis")
from hypothesis import HealthCheck, assume, given, settings
from hypothesis import strategies as st

from app import catalog
from app.envelope import (
    compute_envelope_hash,
    compute_quote_hash,
    verify_quote,
)
from app.models import (
    Cart,
    CartLine,
    EnvelopeSlot,
    EnvelopeStatus,
    MerchantQuote,
    PurchaseEnvelope,
)

CATALOG = catalog.load_catalog()
SKUS = [p["sku"] for p in CATALOG]
ALL_TAGS = sorted({t for p in CATALOG for t in p.get("tags", [])})
ALL_CATEGORIES = sorted({p["category"] for p in CATALOG})

NOW = 1_800_000_000.0

SETTINGS = settings(
    max_examples=300,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture],
)


@pytest.fixture(autouse=True)
def clean_stock():
    catalog.reset_stock()
    yield
    catalog.reset_stock()


# ---------------------------------------------------------------------------
# Grammar
# ---------------------------------------------------------------------------

@st.composite
def envelopes(draw, active_only: bool = False):
    slots = draw(st.lists(
        st.builds(
            EnvelopeSlot,
            id=st.text(min_size=1, max_size=8,
                       alphabet="abcdefghijklmnopqrstuvwxyz"),
            label=st.just("slot"),
            required_tags=st.lists(st.sampled_from(ALL_TAGS), min_size=1, max_size=3,
                                   unique=True),
            quantity=st.integers(min_value=1, max_value=4),
        ),
        min_size=1, max_size=3,
    ))
    status = (EnvelopeStatus.ACTIVE if active_only
              else draw(st.sampled_from(list(EnvelopeStatus))))
    env = PurchaseEnvelope(
        id="env_prop",
        user_id="u",
        agent_id="a",
        label="property test",
        goal="property test",
        merchant_id="merchant_freshbasket",
        max_total_paise=draw(st.integers(min_value=100, max_value=2_000_000)),
        fulfillment_profile_id="dest_demo",
        delivery_deadline=NOW + 3600,
        expires_at=NOW + draw(st.integers(min_value=-600, max_value=3600)),
        slots=slots,
        blocked_categories=draw(st.lists(st.sampled_from(ALL_CATEGORIES),
                                         max_size=3, unique=True)),
        blocked_tags=draw(st.lists(st.sampled_from(ALL_TAGS), max_size=4, unique=True)),
        status=status,
        version=1,
        envelope_hash="",
        created_at=NOW,
        updated_at=NOW,
    )
    return env.model_copy(update={"envelope_hash": compute_envelope_hash(env)})


@st.composite
def quotes(draw, envelope: PurchaseEnvelope, honest_facts: bool = True):
    by_sku = catalog.by_sku()
    chosen = draw(st.lists(st.sampled_from(SKUS), min_size=1, max_size=4, unique=True))
    lines = []
    for sku in chosen:
        p = by_sku[sku]
        lines.append(CartLine(
            sku=sku,
            name=p["name"] if honest_facts else "tampered",
            category=p["category"],
            unit_price_paise=(p["price_paise"] if honest_facts
                              else max(1, p["price_paise"] - 1)),
            qty=draw(st.integers(min_value=1, max_value=4)),
        ))
    q = MerchantQuote(
        merchant_id=envelope.merchant_id,
        currency="INR",
        fulfillment_profile_id=envelope.fulfillment_profile_id,
        delivery_eta=envelope.delivery_deadline - 60,
        cart=Cart(lines=lines),
        substitutions=[],
        quote_hash="",
    )
    return q.model_copy(update={"quote_hash": compute_quote_hash(q)})


@st.composite
def envelope_and_quote(draw, active_only: bool = False, honest_facts: bool = True):
    env = draw(envelopes(active_only=active_only))
    return env, draw(quotes(env, honest_facts=honest_facts))


# ---------------------------------------------------------------------------
# The generator must be capable of producing an ALLOW
# ---------------------------------------------------------------------------

def test_the_grammar_can_produce_authorised_orders():
    """Guard against a vacuous property suite.

    Every property below is of the form "if X then not allowed". If the grammar
    could never produce an allowed decision, all of them would pass while testing
    nothing at all. This asserts the search space actually contains the case that
    matters.
    """
    found = 0
    for i in range(400):
        env_slot = EnvelopeSlot(id="s", label="s", required_tags=["protein"], quantity=1)
        env = PurchaseEnvelope(
            id="env_ok", user_id="u", agent_id="a", label="l", goal="g",
            merchant_id="merchant_freshbasket", max_total_paise=1_000_000,
            fulfillment_profile_id="dest_demo",
            delivery_deadline=NOW + 3600, expires_at=NOW + 3600,
            slots=[env_slot], blocked_categories=[], blocked_tags=[],
            status=EnvelopeStatus.ACTIVE, version=1, envelope_hash="",
            created_at=NOW, updated_at=NOW,
        )
        env = env.model_copy(update={"envelope_hash": compute_envelope_hash(env)})
        from app.envelope import build_quote
        from app.models import AutopilotScenario
        q, _ = build_quote(env, AutopilotScenario.NORMAL, now=NOW + 10)
        if verify_quote(env, q, now=NOW + 10).allowed:
            found += 1
            break
    assert found, "the grammar cannot produce an authorised order; properties are vacuous"


@st.composite
def envelope_and_cart_sharing_a_blocked_tag(draw):
    """A cart line whose product genuinely carries a tag the envelope forbids.

    Built by construction rather than by filtering. `assume()`-ing an accidental
    intersection discards most examples and quietly narrows what the property
    actually covers — the test would still pass while testing almost nothing.
    """
    by_sku = catalog.by_sku()
    sku = draw(st.sampled_from([s for s in SKUS if by_sku[s].get("tags")]))
    blocked = draw(st.sampled_from(by_sku[sku]["tags"]))
    env = draw(envelopes(active_only=True))
    env = env.model_copy(update={"blocked_tags": [blocked], "envelope_hash": ""})
    env = env.model_copy(update={"envelope_hash": compute_envelope_hash(env)})
    return env, draw(quotes(env)), sku, blocked


@st.composite
def envelope_and_cart_sharing_a_blocked_category(draw):
    """Same construction, for the category rule."""
    by_sku = catalog.by_sku()
    sku = draw(st.sampled_from(SKUS))
    category = by_sku[sku]["category"]
    env = draw(envelopes(active_only=True))
    env = env.model_copy(update={"blocked_categories": [category], "envelope_hash": ""})
    env = env.model_copy(update={"envelope_hash": compute_envelope_hash(env)})
    return env, sku


# ---------------------------------------------------------------------------
# Invariants — no labels, no expected outcomes
# ---------------------------------------------------------------------------

@SETTINGS
@given(bundle=envelope_and_cart_sharing_a_blocked_tag())
def test_a_forbidden_tag_is_never_authorised(bundle):
    """The rule a category allowlist cannot express, over arbitrary input."""
    envelope, quote, sku, blocked = bundle
    by_sku = catalog.by_sku()
    # The generated quote may or may not have drawn the SKU; force it in, so
    # every example exercises the property rather than one in nine.
    p = by_sku[sku]
    quote = quote.model_copy(update={
        "cart": Cart(lines=[*quote.cart.lines, CartLine(
            sku=sku, name=p["name"], category=p["category"],
            unit_price_paise=p["price_paise"], qty=1)]),
        "quote_hash": "",
    })
    quote = quote.model_copy(update={"quote_hash": compute_quote_hash(quote)})
    assert blocked in by_sku[sku]["tags"]
    assert not verify_quote(envelope, quote, now=NOW + 10).allowed


@SETTINGS
@given(pair=envelope_and_quote())
def test_the_cap_is_never_exceeded(pair):
    envelope, quote = pair
    assume(quote.cart.total_paise > envelope.max_total_paise)
    assert not verify_quote(envelope, quote, now=NOW + 10).allowed


@SETTINGS
@given(bundle=envelope_and_cart_sharing_a_blocked_category())
def test_a_blocked_category_is_never_authorised(bundle):
    envelope, sku = bundle
    p = catalog.by_sku()[sku]
    q = MerchantQuote(
        merchant_id=envelope.merchant_id, currency="INR",
        fulfillment_profile_id=envelope.fulfillment_profile_id,
        delivery_eta=envelope.delivery_deadline - 60,
        cart=Cart(lines=[CartLine(sku=sku, name=p["name"], category=p["category"],
                                  unit_price_paise=p["price_paise"], qty=1)]),
        substitutions=[], quote_hash="",
    )
    q = q.model_copy(update={"quote_hash": compute_quote_hash(q)})
    assert not verify_quote(envelope, q, now=NOW + 10).allowed


@SETTINGS
@given(pair=envelope_and_quote())
def test_an_envelope_that_is_not_active_is_never_authorised(pair):
    envelope, quote = pair
    assume(envelope.status is not EnvelopeStatus.ACTIVE)
    assert not verify_quote(envelope, quote, now=NOW + 10).allowed


@SETTINGS
@given(pair=envelope_and_quote(active_only=True))
def test_an_expired_envelope_is_never_authorised(pair):
    envelope, quote = pair
    at = envelope.expires_at + 1
    assert not verify_quote(envelope, quote, now=at).allowed


@SETTINGS
@given(pair=envelope_and_quote(active_only=True, honest_facts=False))
def test_tampered_catalog_facts_are_never_authorised(pair):
    """The buyer's asserted price never has authority over the server's."""
    envelope, quote = pair
    assert not verify_quote(envelope, quote, now=NOW + 10).allowed


@SETTINGS
@given(pair=envelope_and_quote(active_only=True), bump=st.integers(1, 5_000))
def test_a_quote_whose_hash_was_not_recomputed_is_never_authorised(pair, bump):
    """Mutate a hashed field and leave the digest behind."""
    envelope, quote = pair
    forged = quote.model_copy(update={"delivery_eta": quote.delivery_eta + bump})
    assert not verify_quote(envelope, forged, now=NOW + 10).allowed


@SETTINGS
@given(pair=envelope_and_quote(active_only=True))
def test_insufficient_stock_is_never_authorised(pair):
    envelope, quote = pair
    short = quote.cart.lines[0]
    catalog.set_stock(short.sku, max(0, short.qty - 1))
    assert not verify_quote(envelope, quote, now=NOW + 10).allowed


@SETTINGS
@given(pair=envelope_and_quote(active_only=True))
def test_a_widened_envelope_is_never_authorised(pair):
    """Loosen the rules after approval without re-hashing."""
    envelope, quote = pair
    assume(envelope.blocked_tags or envelope.blocked_categories)
    widened = envelope.model_copy(update={"blocked_tags": [], "blocked_categories": []})
    # envelope_hash still carries the pre-widening digest.
    assert not verify_quote(widened, quote, now=NOW + 10).allowed


# ---------------------------------------------------------------------------
# Structural invariants — must hold for every input, allowed or not
# ---------------------------------------------------------------------------

@SETTINGS
@given(pair=envelope_and_quote())
def test_authorisation_is_deterministic(pair):
    envelope, quote = pair
    a = verify_quote(envelope, quote, now=NOW + 10)
    b = verify_quote(envelope, quote, now=NOW + 10)
    assert (a.allowed, a.code, [d.model_dump() for d in a.deltas]) == \
           (b.allowed, b.code, [d.model_dump() for d in b.deltas])


@SETTINGS
@given(pair=envelope_and_quote())
def test_allowed_implies_no_deltas_and_the_converse(pair):
    """`allowed` and `deltas` must never disagree — one screen renders both."""
    envelope, quote = pair
    d = verify_quote(envelope, quote, now=NOW + 10)
    assert d.allowed == (not d.deltas)


@SETTINGS
@given(pair=envelope_and_quote())
def test_every_delta_carries_a_recovery_a_caller_can_act_on(pair):
    """A refusal with no route forward is a dead end, and this layer sells the
    route forward. Every delta must say which one it is."""
    envelope, quote = pair
    for delta in verify_quote(envelope, quote, now=NOW + 10).deltas:
        assert delta.recovery in ("repair", "fresh_approval", "stop")
        assert delta.field and delta.expected and delta.actual


@SETTINGS
@given(pair=envelope_and_quote())
def test_a_decision_never_reports_a_total_it_did_not_compute(pair):
    envelope, quote = pair
    d = verify_quote(envelope, quote, now=NOW + 10)
    assert d.quote_total_paise == quote.cart.total_paise
    assert d.envelope_id == envelope.id
    assert d.envelope_version == envelope.version


@st.composite
def envelope_and_satisfying_quote_with_semantic_drift(draw):
    """An active envelope, a quote satisfying every slot, and one extra line
    whose tags satisfy no slot."""
    by_sku = catalog.by_sku()
    chosen_skus = draw(st.lists(
        st.sampled_from([s for s in SKUS if by_sku[s].get("tags")]),
        min_size=1, max_size=3, unique=True,
    ))
    slots = []
    lines = []
    for i, sku in enumerate(chosen_skus):
        p = by_sku[sku]
        qty = draw(st.integers(min_value=1, max_value=2))
        slots.append(EnvelopeSlot(
            id=f"slot_{i}",
            label=f"Slot {i}",
            required_tags=list(p["tags"]),
            quantity=qty,
        ))
        lines.append(CartLine(
            sku=sku,
            name=p["name"],
            category=p["category"],
            unit_price_paise=p["price_paise"],
            qty=qty,
        ))

    candidates = [
        p for p in CATALOG
        if p["sku"] not in chosen_skus
        and not any(set(s.required_tags).issubset(set(p.get("tags", []))) for s in slots)
        and catalog.available_stock(p["sku"]) >= 1
    ]
    assume(candidates)
    extra = draw(st.sampled_from(candidates))
    extra_line = CartLine(
        sku=extra["sku"],
        name=extra["name"],
        category=extra["category"],
        unit_price_paise=extra["price_paise"],
        qty=1,
    )

    now = NOW + 100
    expiry_offset = draw(st.integers(min_value=60, max_value=7200))
    expires_at = now + expiry_offset
    delivery_deadline = expires_at + 3600

    base_total = sum(l.unit_price_paise * l.qty for l in lines) + extra_line.unit_price_paise
    cap = draw(st.integers(min_value=base_total, max_value=base_total + 10_000_000))

    env = PurchaseEnvelope(
        id=f"env_{draw(st.integers(1, 100000))}",
        user_id="u",
        agent_id="a",
        label="semantic drift property",
        goal="semantic drift property",
        merchant_id=draw(st.sampled_from(["merchant_freshbasket", "merchant_other", "m_123"])),
        max_total_paise=cap,
        fulfillment_profile_id="dest_demo",
        delivery_deadline=delivery_deadline,
        expires_at=expires_at,
        slots=slots,
        blocked_categories=[],
        blocked_tags=[],
        status=EnvelopeStatus.ACTIVE,
        version=1,
        envelope_hash="",
        created_at=NOW,
        updated_at=NOW,
    )
    env = env.model_copy(update={"envelope_hash": compute_envelope_hash(env)})

    quote = MerchantQuote(
        merchant_id=env.merchant_id,
        currency="INR",
        fulfillment_profile_id=env.fulfillment_profile_id,
        delivery_eta=delivery_deadline - 60,
        cart=Cart(lines=[*lines, extra_line]),
        substitutions=[],
        quote_hash="",
    )
    quote = quote.model_copy(update={"quote_hash": compute_quote_hash(quote)})
    return env, quote, now


@SETTINGS
@given(bundle=envelope_and_satisfying_quote_with_semantic_drift())
def test_semantic_drift_extra_line_is_never_authorised(bundle):
    """For any envelope and any quote that satisfies every slot, appending one
    extra line whose tags satisfy no slot always yields allowed=False with a
    cart.lines[...] delta — for every cap, every merchant, every clock value
    inside the expiry."""
    envelope, quote, check_time = bundle
    decision = verify_quote(envelope, quote, now=check_time)
    assert not decision.allowed
    assert decision.code == "BLOCK_ENVELOPE_MISMATCH"
    assert any(d.field.startswith("cart.lines[") for d in decision.deltas)
